title: Anis Bhimani # your name (or website title) here
logo: "/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced Data Science Leader  
  <br><br>
  8 years experience in Data Science &
  <br>
  3 years in DS Leadership 
  <br><br>
  <a href="https://www.linkedin.com/in/anisbhimani/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 4284016951 # your Google Analytics tracking ID here
